### PR TITLE
Feature/4 ckeditor support

### LINKED ISSUE #4: Add support for CKEditor nested entry types

### LINKED ISSUE #6: contextHandle per block setting not working
Given a block with the following settings definition:

```php
    protected function onInit(ContextBlockSettings $settings): void
    {
        $settings
            ->contextHandle('banner')
            ->matrixHandle('banner');
    }
```

The context for this block should be added to the `banner` object, but it's still being added to the `blocks` object.

### PR DESCRIPTION
**Pull request by vanrez-nez**
closes #4
related #6 #2 

Notes:
- I've updated the Readme to match new usage.
- There's a new method in the `ContextBlock` class called `getMarkupContext(string $markup): array` for cases where content coming from Ckeditor needs to be processed, altough this is optional if no extra processing is done. Internally each `markup` `chunk` coming from Ckeditor content will output a descriptor with the context ready to be rendered or used as a context for other component.
- This version is not backward compatible with hooks.
- It implements the cache as a plugin service, allowing the cache files to be stored in a separated folder (`/storage/runtime/cache_blocks`), it exposes a new item to be cleared individually from CMS: `admin/utilities/clear-caches` or from the console using `php craft clear-caches/block-loader`
- It refactors the class detection using standard Autoloader from CraftCMS.

### CODE REVIEW

**Comment by daltonrooney** [comment]
@vanrez-nez Thanks, this is looking great. I appreciate the ability to clear the blocks cache separately from the other caches and especially for the console, I think we'll want to include this in the documentation and in our deployment scripts. 

I have a question about the `templateHandle` setting: if I apply that setting to a block, that should change the value of the `templateHandle` on the contextDescriptor object for that block? 

Testing this on https://github.com/madebyraygun/craft-component-library-demo/blob/da772965f9c3a1197b20412ec315239aaf8bfe82/modules/blocks/TextBannerBlock.php#L14

Dumping the block looks like this:
```php
madebyraygun\blockloader\base\ContextDescriptor {#689 ▼
  +id: "85"
  +order: 1
  +cacheable: true
  +fieldHandle: "banner"
  +templateHandle: "text-banner"
  +context: array:2 [▼
    "heading" => "Ipsum minim ad eu anim"
    "text" => "Amet elit quis sit et anim elit aliquip consectetur ut ex dolore sit."
  ]
}
```

My include looks like `{% include '@modules/banner/' ~ item.templateHandle with item.context %}`, trying to pull in the `@modules/banner/text` component.

**Comment by vanrez-nez** [comment]
@daltonrooney oops! sorry forgot to mention `onInit` was renamed to `setSettings` receiving no params to save us from having to include the `use madebyraygun\blockloader\base\ContextBlockSettings` declaration on each file:

```php
public function setSettings(): void
    {
        $this->settings
            ->templateHandle('@components/image')
            ->eagerFields(['image']);
    }
```

**Comment by daltonrooney** [comment]
Thanks, that worked perfectly! Two thoughts:

1) Moving over to the Craft autoloader is brilliant, but has the downside that you have to run `composer dump-autoload` every time you define a new block. We should document this so that it's clear.

2) Maybe we should disable caching when devmode is enabled? Or add a global setting for enableCaching that overrides the local block settings? I just noticed in dev that I had to clear the cache every time I made a change to the block data, that may be confusing or get annoying during dev.

**Comment by vanrez-nez** [comment]
@daltonrooney thanks! this is ready! I've keept both autoloader and filescanning options since I think theres value for the developer in avoiding `composer dump-autoload` exec on files changes. For this I'm using https://github.com/composer/class-map-generator (internally what composer autoload uses) to map the classes from the files. Let me know what you think!

**Comment by daltonrooney** [comment]
This is great! I’m going to run a couple more test scenarios and prep for release. 👍🏻

**Pull request merged**
